### ISSUE TITLE
Fails on Fedora 36 - conan-sigpp

### ISSUE THREAD

**Issue by ThePowerTool** [worldforge/conan-packages#1]
Hi,

I am following the instructions:
```
conan remote add worldforge https://artifactory.ogenvik.org/artifactory/api/conan/conan
mkdir build && cd build
conan install .. --build missing
```
at which point the "conan install" fails with:
```
*********************************************************
Recipe 'sigc++/2.10.0@worldforge/stable' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'sigc++/2.10.0@worldforge/stable' not resolved: sigc++/2.10.0@worldforge/stable: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools, MSBuild, AutoToolsBuildEnvironment
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)
```

A quick check of /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py shows Sigcpp pointing to https://github.com/bincrafters/conan-sigcpp

It seems that conan-sigcpp was obsoleted in 2019.

I'd really like to get WorldForge running.  Any help would be sincerely appreciated.

Thank you very much, in advance!

**Comment by ThePowerTool** [comment]
Additional Info:  Just FYI, the workaround for this seems to be copying https://github.com/conan-io/conan-center-index/blob/7d5cd85df85ff82887f3f1a79c788ec5442f648b/recipes/libsigcpp/3.x.x/conanfile.py into my /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py

I do not know if "/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py" will be the same reference for other install so this may come down to identifying the location of the conanfile.py for the referenced library.

**Comment by erikogenvik** [comment]
I've updated the component of Worldforge that uses sigc++ to instead use the "libsigcpp" recipe from Conan Center, which would make this one obsolete.
