### ISSUE TITLE
Fails on Fedora 36 - libxdg-basedir

### ISSUE THREAD

**Issue by ThePowerTool** [worldforge/conan-packages#2]
`] conan install .. --build missing`
Results in:
```
*********************************************************
Recipe 'libxdg-basedir/1.2.3@worldforge/stable' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'libxdg-basedir/1.2.3@worldforge/stable' not resolved: libxdg-basedir/1.2.3@worldforge/stable: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/libxd442a2ef979ec8/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/libxd442a2ef979ec8/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/libxd442a2ef979ec8/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools, AutoToolsBuildEnvironment
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)
```

Workaround:
In /root/.conan2/p/libxd442a2ef979ec8/e/conanfile.py
change:
```
from conans import ConanFile, tools, AutoToolsBuildEnvironment
import os
```
to:
```
from conan import ConanFile
from conan.tools.files import save, load
from conan.tools.gnu import AutotoolsToolchain, AutotoolsDeps
from conan.tools.microsoft import unix_path, VCVars, is_msvc
from conan.errors import ConanInvalidConfiguration
from conan.errors import ConanException
import os
```

**Comment by erikogenvik** [comment]
All of the Conan packages are incompatible with Conan 2. I'm in the process of updating them right now.

**Comment by ThePowerTool** [comment]
Hi Eric,

I have a question for you:

As you may have noticed in issues under conan-packages, I posted the changes I made to support conan 2.0.  I also know you have seen me attempting to install the server and client.

As a result of my attempts here I have engaged in the conan community.  They provided me with pointers on "how to get started" in conan, WorldForge, and github.  While I have been installing code from source and using github for quite some time I'm still a neophyte.

Is the work that I have done (e.g. the conan upgrade replacement code, above) helpful?  Should I look at contributing by figuring out how to put it into github so you can merge it into your code base?

I also realize it may simply be cut-and-paste and you might play to simply grab it from these issues.  I'm just wondering if my help, here (regarding my conan 2.0 upgrade efforts), would be received as positive and productive input.

Thanks!

**Comment by erikogenvik** [comment]
Hi, you helping out with upgrading to Conan 2 is greatly appreciated. I have some changes I've done to the recipes here, but I haven't been able to push it yet. The best way to contribute is to fork the repo and create a Pull Request. Some of the fixes should however go into Conan Center, rather than having the recipes copied to here and fixed here.
