### ISSUE TITLE
Fails on Fedora 36 - cpython

### ISSUE THREAD

**Issue by ThePowerTool** [worldforge/conan-packages#4]
`] conan install .. --build missing`
Results in:
```
*********************************************************
Recipe 'cpython/3.10.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'cpython/3.10.0' not resolved: cpython/3.10.0: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/cpyth54b7acf007792/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/cpyth54b7acf007792/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/cpyth54b7acf007792/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, MSBuild, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)
```

Workaround:
In /root/.conan2/p/cpyth54b7acf007792/e/conanfile.py

Important Note:  Please read the warnings below before using the pastebin conan 2.0 linked file.

[cpython conan 2.0 conanfile.py](https://pastebin.com/24NPC4Ad)

Warning!
This is a file I updated until it worked for me on my system.  Please note:
. This may not work on your system
. I only updated it to work for me on my system (yes, repeating)
. I do not understand versioning and changed the zlib version (static var) to match so the install would complete
. I *likely* missed and/or didn't update other items in this script
. I am including detail on the errors I encountered and actions taken so someone following this hopefully has an easier time than I did

Here are my notes, in detail:
. /root/.conan2/p/cpyth54b7acf007792/e/conanfile.py
ERROR: Package 'cpython/3.10.0' not resolved: cpython/3.10.0: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/cpyth54b7acf007792/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/cpyth54b7acf007792/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/cpyth54b7acf007792/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, MSBuild, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)

ref: https://github.com/worldforge/conan-packages/issues/4
Action:
Replaced header, replace objects, update conan build file (conanfile.txt) in ~./cyphesis:
Replace "Visual Studio" with "msvc"
Replaced header:
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.scm import Version
from conan.tools.apple import is_apple_os
from conan.tools.files import (
    apply_conandata_patches, collect_libs, copy, export_conandata_patches, get,
    rename, replace_in_file, rmdir, save
)
import glob
import os
import re
import textwrap

required_conan_version = ">=1.53.0"

Replace (remove) "tools." prefix (in body; e.g. tools.Version())

ERROR: cpython/3.10.0: Error in requirements() method, line 196
	if not is_apple_os(self.settings.os):
	ConanException: 'settings.os.settings' doesn't exist for 'Linux'
'settings.os' possible configurations are none
Note: is_apple_os() pre-sets "settings.os" (which becomes redundant) leaving is_apple_os(self) 

Action:
Update: is_apple_os(self.settings.os)
    to: is_apple_os(self)

ERROR: Version conflict: cpython/3.10.0->zlib/1.2.11, None->zlib/1.2.13.

trying updating:
        self.requires("zlib/1.2.11")
to:
        self.requires("zlib/1.2.13")

**Comment by erikogenvik** [comment]
The fixes to this recipe should be done in Conan Center. We could copy the recipe to here and fix it, and that would work, but a more preferred fix would be in Conan Center.
